hw_env:
    env_type: virt
    libvirt_type: qemu
    network_cidr: 192.168.0.0/24
    floating_ip_end: 172.16.23.50
    floating_ip_start: 172.16.23.40
    floating_ip_cidr: 172.16.23.0/24
    network_gateway: 172.16.23.251
    network_type: vlan
    physical_network: datacentre
    ExternalNetworkVlanID: 10
    dns_server: 192.168.122.1
