hw_env:
  env_type: quintupleo_host_cloud
  network_cidr: 192.168.0.0/24
  network: '172.25.0'
  floating_ip_end: 172.25.0.100
  floating_ip_start: 172.25.0.50
  floating_ip_cidr: 172.25.0.0/16
  network_gateway: 172.25.0.1
  network_type: flat
  physical_network: datacentre
  ExternalNetworkVlanID: null
